# Generated by Django 5.2.3 on 2025-06-29 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='公司名称')),
                ('title', models.CharField(max_length=100, verbose_name='职位名称')),
                ('salary', models.CharField(blank=True, max_length=100, verbose_name='薪资')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='工作地点')),
                ('status', models.CharField(choices=[('not_applied', '未投递'), ('applied', '已投递'), ('interviewed', '已面试'), ('offer', '已拿offer'), ('rejected', '已拒绝'), ('waiting', '待定')], default='not_applied', max_length=20, verbose_name='投递状态')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('data_applied', models.DateField(blank=True, null=True, verbose_name='投递日期')),
                ('link', models.URLField(blank=True, verbose_name='职位链接')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
